# Site settings
title: xinminds.tk
email: xinminds@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  xinminds -- somewhere to write down my thoughts
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.xinminds.tk" # the base hostname & protocol for your site
#twitter_username: xinminds
github_username:  xinminds

# Build settings
markdown: kramdown
